/* Independently authored Tallynest compatibility boundary. */
export const CSV_AT_LEAST_ONE_ROW_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const CSV_EMPTY_COLUMN_HEADERS_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const CSV_FILES_ONLY_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const CSV_FILE_TOO_LARGE_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const CSV_INCONSISTENT_COLUMNS_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const CSV_MAX_RECORDS_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const CSV_PARSE_ERROR_CODE = "TALLYNEST_UNAVAILABLE";
export const MAX_CSV_VALUES = "TALLYNEST_UNAVAILABLE";
