import "server-only";
export const getIsAISmartToolsEnabled = async () => Boolean(process.env.OPENAI_API_KEY || process.env.AI_OPENAI_COMPATIBLE_API_KEY);
export const getAccessControlPermission = async () => false;
export const getIsMultiOrgEnabled = async () => false;
export const getIsTwoFactorAuthEnabled = async () => false;
export const getWhiteLabelPermission = async () => false;
export const getIsContactsEnabled = async () => false;
export const getIsQuotasEnabled = async () => false;
export const getIsFeedbackDirectoriesEnabled = async () => false;
export const getBiggerUploadFileSizePermission = async () => false;
export const getIsSpamProtectionEnabled = async () => false;
export const getIsWorkflowsEnabled = async () => false;
export const getBulkInvitePermission = async () => false;
export const getIsSamlSsoEnabled = async () => false;
export const getIsSsoEnabled = async () => false;
export const getRemoveBrandingPermission = async () => false;
export const getOrganizationWorkspacesLimit = async () => Number(process.env.TALLYNEST_MAX_WORKSPACES_PER_ORGANIZATION ?? 10);
