import "server-only";
export const getIsAISmartToolsEnabled = async (..._args: unknown[]) => Boolean(process.env.OPENAI_API_KEY || process.env.AI_OPENAI_COMPATIBLE_API_KEY);
export const getAccessControlPermission = async (..._args: unknown[]) => false;
export const getIsMultiOrgEnabled = async (..._args: unknown[]) => false;
export const getIsTwoFactorAuthEnabled = async (..._args: unknown[]) => false;
export const getWhiteLabelPermission = async (..._args: unknown[]) => false;
export const getIsContactsEnabled = async (..._args: unknown[]) => false;
export const getIsQuotasEnabled = async (..._args: unknown[]) => false;
export const getIsFeedbackDirectoriesEnabled = async (..._args: unknown[]) => false;
export const getBiggerUploadFileSizePermission = async (..._args: unknown[]) => false;
export const getIsSpamProtectionEnabled = async (..._args: unknown[]) => false;
export const getIsWorkflowsEnabled = async (..._args: unknown[]) => false;
export const getBulkInvitePermission = async (..._args: unknown[]) => false;
export const getIsSamlSsoEnabled = async (..._args: unknown[]) => false;
export const getIsSsoEnabled = async (..._args: unknown[]) => false;
export const getRemoveBrandingPermission = async (..._args: unknown[]) => false;
export const getOrganizationWorkspacesLimit = async (..._args: unknown[]) => Number(process.env.TALLYNEST_MAX_WORKSPACES_PER_ORGANIZATION ?? 10);
