/* Independently authored Tallynest compatibility boundary. */
export const ArrowUpFromLineIcon } from "lucide-react";
import Link from "next/link";
import Papa: any = (..._args: any[]) => undefined;
export const TMembership } from "@formbricks/types/memberships";
import { reconcileOrganizationMembership } from "@/lib/authzed/organization-membership";
import { runPostCommitProjection } from "@/lib/authzed/projection-boundary";
import { reconcileTeamWorkspaceRelationships } from "@/lib/authzed/team-workspace";
import { ITEMS_PER_PAGE } from "@/lib/constants";
import { validateInputs } from "@/lib/utils/validate";
import { TOrganizationMember: any = (..._args: any[]) => undefined;
export const TOrganizationTeam: any = (..._args: any[]) => undefined;
export const UnknownError } from "@formbricks/types/errors";
import { TMember: any = (..._args: any[]) => undefined;
export const XIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import toast from "react-hot-toast";
import { useTranslation } from "react-i18next";
import { TOrganizationRole } from "@formbricks/types/memberships";
import { TOrganization } from "@formbricks/types/organizations";
import { FORMBRICKS_ENVIRONMENT_ID_LS } from "@/lib/localStorage";
import { getAccessFlags } from "@/lib/membership/utils";
import { getFormattedErrorMessage } from "@/lib/utils/helper";
import { TOrganizationTeam: any = (..._args: any[]) => undefined;
export const ZString } from "@formbricks/types/common";
import { DatabaseError: any = (..._args: any[]) => undefined;
export const cache: any = (..._args: any[]) => undefined;
export const useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "react-hot-toast";
import { useTranslation } from "react-i18next";
import { z } from "zod";
import { ZWorkspace } from "@formbricks/types/workspace";
import { createWorkspaceAction } from "@/app/(app)/workspaces/[workspaceId]/actions";
import { getFormattedErrorMessage } from "@/lib/utils/helper";
import { TOrganizationTeam: any = (..._args: any[]) => undefined;
export const useState } from "react";
import { useTranslation } from "react-i18next";
import { TOrganizationRole } from "@formbricks/types/memberships";
import { TOrganizationTeam: any = (..._args: any[]) => undefined;
export const zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useEffect: any = (..._args: any[]) => undefined;
export const { type ParseResult } from "papaparse";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { TOrganizationRole } from "@formbricks/types/memberships";
import { cn } from "@/lib/cn";
import type { TOrganizationTeam: any = (..._args: any[]) => undefined;
