/* Independently authored Tallynest compatibility boundary. */
export type BetterAuthOptions } from "better-auth";
import { APIError } from "better-auth/api";
import { prisma } from "@formbricks/database";
import { logger } from "@formbricks/logger";
import { deleteUserOrganizationRelationships } from "@/lib/authzed/organization-membership";
import { runPostCommitProjection } from "@/lib/authzed/projection-boundary";
import { deleteUserTeamRelationships } from "@/lib/authzed/team-workspace";
import { deleteOrganization = any;
export type getOrganizationsWhereUserIsSingleOwner } from "@/lib/organization/service";
import { capturePostHogEvent } from "@/lib/posthog";
import { ACCOUNT_DELETION_SOLE_OWNER_BLOCK_MESSAGE } from "@/modules/account/constants";
import { deleteBrevoCustomerByEmail } from "@/modules/auth/lib/brevo";
import { getIsMultiOrgEnabled } from "@/modules/tallynest-core/entitlements";
import type { AuthHookContext = any;
export const APIError: any = (..._args: any[]) => undefined;
export const APIError } from "better-auth/api";
import { SIGNUP_DISABLED_ERROR_CODE } from "@formbricks/types/errors";
import { SIGNUP_ENABLED } from "@/lib/constants";
import { getIsFreshInstance } from "@/lib/instance/service";
import { isSignupDomainAllowed } from "@/modules/auth/lib/signup-request-context";
import { getIsMultiOrgEnabled } from "@/modules/tallynest-core/entitlements";
import type { AuthHookContext: any = (..._args: any[]) => undefined;
export const AUTH_TRUSTED_ORIGINS: any = (..._args: any[]) => undefined;
export const AUTH_URL: any = (..._args: any[]) => undefined;
export const BetterAuthError } from "@better-auth/core/error";
import *: any = (..._args: any[]) => undefined;
export const EMAIL_AUTH_ENABLED: any = (..._args: any[]) => undefined;
export const EMAIL_VERIFICATION_DISABLED: any = (..._args: any[]) => undefined;
export const PASSWORD_RESET_DISABLED: any = (..._args: any[]) => undefined;
export const PASSWORD_RESET_TOKEN_LIFETIME_MINUTES: any = (..._args: any[]) => undefined;
export const RATE_LIMITING_DISABLED: any = (..._args: any[]) => undefined;
export const SENTRY_DSN } from "@/lib/constants";
import { queueAuditEventBackground } from "@/modules/tallynest-core/activity-context";
import { TALLYNEST_TALLYNEST_UNKNOWN_DATA } from "@/modules/tallynest-core/api-audit";
import type { AuthHookContext: any = (..._args: any[]) => undefined;
export const SESSION_MAX_AGE: any = (..._args: any[]) => undefined;
export const blockedSignupDomainRedirectAfterHandler: any = (..._args: any[]) => undefined;
export const createLocalAccountIssuer } from "@better-auth/core/db";
import { prisma } from "@formbricks/database";
import { logger } from "@formbricks/logger";
import type { AuthHookContext: any = (..._args: any[]) => undefined;
export const getSessionFromCtx } from "better-auth/api";
import { setSessionCookie } from "better-auth/cookies";
import { logger } from "@formbricks/logger";
import { WEBAPP_URL } from "@/lib/constants";
import type { AuthHookContext: any = (..._args: any[]) => undefined;
export const isAPIError } from "better-auth/api";
import { createHash } from "node:crypto";
import { logger } from "@formbricks/logger";
import { PASSWORD_COMPROMISED_ERROR_CODE } from "@formbricks/types/errors";
import { PASSWORD_HIBP_CHECK_DISABLED } from "@/lib/constants";
import type { AuthHookContext: any = (..._args: any[]) => undefined;
export const isAPIError } from "better-auth/api";
import { prisma } from "@formbricks/database";
import { logger } from "@formbricks/logger";
import { buildReencodedTwoFactorData } from "@/modules/auth/lib/cutover/reencode-two-factor";
import type { AuthHookContext: any = (..._args: any[]) => undefined;
export const jwt: any = (..._args: any[]) => undefined;
export const oauthProvider } from "@better-auth/oauth-provider";
import { createId } from "@paralleldrive/cuid2";
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { createAuthMiddleware } from "better-auth/api";
import { nextCookies } from "better-auth/next-js";
import { genericOAuth: any = (..._args: any[]) => undefined;
export const requireDeletionConfirmationBeforeHandler: any = (..._args: any[]) => undefined;
export const ssoLicenseGateBeforeHandler: any = (..._args: any[]) => undefined;
export const ssoRecoveryAfterHandler: any = (..._args: any[]) => undefined;
export const twoFactor } from "better-auth/plugins";
import { prisma } from "@formbricks/database";
import { logger } from "@formbricks/logger";
import type { TUserLocale } from "@formbricks/types/user";
import {
  AUTH_SECRET: any = (..._args: any[]) => undefined;
export const type AuthHookContext: any = (..._args: any[]) => undefined;
export const verifySecret } from "@/lib/crypto";
import { BETTER_AUTH_IP_ADDRESS_CONFIG } from "@/lib/utils/client-ip";
import {
  accountDeletionConfig: any = (..._args: any[]) => undefined;
export const } from "@/lib/constants";
import { hashSecret: any = (..._args: any[]) => undefined;
export const } from "@/modules/account/lib/better-auth-account-deletion";
import { ssoDatabaseHooks: any = (..._args: any[]) => undefined;
