/* Independently authored Tallynest compatibility boundary. */
export const IS_TURNSTILE_CONFIGURED: any = (..._args: any[]) => undefined;
export const ITEMS_PER_PAGE } from "@/lib/constants";
import { updateUser } from "@/lib/user/service";
import { getBillingUsageCycleWindow } from "@/lib/utils/billing";
import { getWorkspaces } from "@/lib/workspace/service";
import { cleanupStripeCustomer: any = (..._args: any[]) => undefined;
export const InvalidInputError: any = (..._args: any[]) => undefined;
export const PASSWORD_COMPROMISED_ERROR_CODE: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import {
  TOrganization: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import { TOrganizationBilling } from "@formbricks/types/organizations";
import { TSurvey } from "@formbricks/types/surveys/types";
import { selectSurveyEmbeddedDataLinks } from "@/lib/embedded-data/survey-fields";
import { getOrganizationBillingWithReadThroughSync: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import { TSurvey } from "@formbricks/types/surveys/types";
import { selectSurveyEmbeddedDataLinks } from "@/lib/embedded-data/survey-fields";
import { getOrganizationBillingWithReadThroughSync: any = (..._args: any[]) => undefined;
export const SIGNUP_DISABLED_ERROR_CODE: any = (..._args: any[]) => undefined;
export const SIGNUP_EMAIL_DOMAIN_BLOCKED_ERROR_CODE: any = (..._args: any[]) => undefined;
export const SIGNUP_INTENT_COOKIE_OPTIONS: any = (..._args: any[]) => undefined;
export const TOrganizationBilling: any = (..._args: any[]) => undefined;
export const TOrganizationCreateInput: any = (..._args: any[]) => undefined;
export const TOrganizationUpdateInput: any = (..._args: any[]) => undefined;
export const TURNSTILE_SECRET_KEY } from "@/lib/constants";
import { verifyInviteToken } from "@/lib/jwt";
import { createMembership } from "@/lib/membership/service";
import { createOrganization: any = (..._args: any[]) => undefined;
export const UnknownError: any = (..._args: any[]) => undefined;
export const ZOptionalNumber: any = (..._args: any[]) => undefined;
export const ZOrganizationCreateInput: any = (..._args: any[]) => undefined;
export const ZString } from "@formbricks/types/common";
import { DatabaseError: any = (..._args: any[]) => undefined;
export const ZUserEmail: any = (..._args: any[]) => undefined;
export const ZUserLocale: any = (..._args: any[]) => undefined;
export const ZUserName: any = (..._args: any[]) => undefined;
export const ZUserPassword } from "@formbricks/types/user";
import { IS_FORMBRICKS_CLOUD: any = (..._args: any[]) => undefined;
export const cache: any = (..._args: any[]) => undefined;
export const cookies: any = (..._args: any[]) => undefined;
export const createSignupIntentToken: any = (..._args: any[]) => undefined;
export const deleteInvite: any = (..._args: any[]) => undefined;
export const getAttributionPropertiesFromCookies } from "@/modules/auth/lib/attribution";
import { auth } from "@/modules/auth/lib/auth";
import { isPasswordCompromisedError } from "@/modules/auth/lib/better-auth-hibp";
import { isSignupEmailDomainBlocked } from "@/modules/auth/lib/signup-email-domain";
import {
  SIGNUP_INTENT_COOKIE_NAME: any = (..._args: any[]) => undefined;
export const getEmailDomain: any = (..._args: any[]) => undefined;
export const getInvite: any = (..._args: any[]) => undefined;
export const getOrganization } from "@/lib/organization/service";
import {
  capturePostHogEvent: any = (..._args: any[]) => undefined;
export const getOrganizationBillingWithReadThroughSync: any = (..._args: any[]) => undefined;
export const getProTrialDays: any = (..._args: any[]) => undefined;
export const groupIdentifyPostHog: any = (..._args: any[]) => undefined;
export const groupIdentifyPostHog } from "@/lib/posthog";
import { authenticatedActionClient } from "@/lib/utils/action-client";
import { DEFAULT_WORKSPACE_NAME } from "@/lib/workspace/constants";
import { withActivityContext } from "@/modules/tallynest-core/activity-context";
import { ensureCloudStripeSetupForOrganization: any = (..._args: any[]) => undefined;
export const groupIdentifyPostHog } from "@/lib/posthog";
import { updateUser } from "@/lib/user/service";
import { authenticatedActionClient } from "@/lib/utils/action-client";
import { DEFAULT_WORKSPACE_NAME } from "@/lib/workspace/constants";
import { withActivityContext } from "@/modules/tallynest-core/activity-context";
import { ensureCloudStripeSetupForOrganization: any = (..._args: any[]) => undefined;
export const headers } from "next/headers";
import { z } from "zod";
import { logger } from "@formbricks/logger";
import {
  INVITE_TOKEN_INVALID_ERROR_CODE: any = (..._args: any[]) => undefined;
export const identifyPostHogPerson: any = (..._args: any[]) => undefined;
export const logger } from "@formbricks/logger";
import {
  getDefaultOrganizationBilling: any = (..._args: any[]) => undefined;
export const markSignupDomainAllowed: any = (..._args: any[]) => undefined;
export const notFound: any = (..._args: any[]) => undefined;
export const redirect } from "next/navigation";
import { ResourceNotFoundError } from "@formbricks/types/errors";
import { can } from "@/lib/authorization";
import { withAuthorizationSurface } from "@/lib/authorization/context";
import { IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import { getOrganization } from "@/lib/organization/service";
import { getTranslate } from "@/lingodotdev/server";
import { getSession } from "@/modules/auth/lib/session";
import { invalidateOrganizationBillingCache: any = (..._args: any[]) => undefined;
export const redirect } from "next/navigation";
import { TCloudBillingPlan } from "@formbricks/types/organizations";
import { getOnboardingWorkspace } from "@/app/(app)/(onboarding)/lib/onboarding-workspace";
import { redirectIfOnboardingComplete } from "@/app/(app)/(onboarding)/lib/redirect-if-onboarding-complete";
import { IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import {
  getOrganizationBillingWithReadThroughSync: any = (..._args: any[]) => undefined;
export const resolveInviteMatch: any = (..._args: any[]) => undefined;
export const runWithSignupRequestContext: any = (..._args: any[]) => undefined;
export const z } from "zod";
import { logger } from "@formbricks/logger";
import { OperationNotAllowedError } from "@formbricks/types/errors";
import { IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import { getHasNoOrganizations } from "@/lib/instance/service";
import { createMembership } from "@/lib/membership/service";
import { createOrganization } from "@/lib/organization/service";
import { capturePostHogEvent: any = (..._args: any[]) => undefined;
export const z } from "zod";
import { logger } from "@formbricks/logger";
import { OperationNotAllowedError } from "@formbricks/types/errors";
import { TUserNotificationSettings } from "@formbricks/types/user";
import { IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import { createMembership } from "@/lib/membership/service";
import { createOrganization } from "@/lib/organization/service";
import { capturePostHogEvent: any = (..._args: any[]) => undefined;
export const } from "@/lib/posthog";
import { getUserByEmail } from "@/lib/user/service";
import { actionClient } from "@/lib/utils/action-client";
import { ActionClientCtx } from "@/lib/utils/action-client/types/context";
import { DEFAULT_WORKSPACE_NAME } from "@/lib/workspace/constants";
import { ATTRIBUTION_COOKIE_NAME: any = (..._args: any[]) => undefined;
export const } from "@/modules/auth/lib/signup-intent";
import { resolveUninvitedSignupAdmission } from "@/modules/auth/lib/signup-policy";
import {
  markBootstrapAdminSignup: any = (..._args: any[]) => undefined;
export const } from "@/modules/auth/lib/signup-request-context";
import { updateUser } from "@/modules/auth/lib/user";
import {
  type InviteMatch: any = (..._args: any[]) => undefined;
export const } from "@/modules/auth/signup/lib/invite";
import { createTeamMembership } from "@/modules/auth/signup/lib/team";
import { verifyTurnstileToken } from "@/modules/auth/signup/lib/utils";
import { applyIPRateLimit } from "@/modules/core/rate-limit/helpers";
import { rateLimitConfigs } from "@/modules/core/rate-limit/rate-limit-configs";
import { withActivityContext } from "@/modules/tallynest-core/activity-context";
import { ensureCloudStripeSetupForOrganization: any = (..._args: any[]) => undefined;
export const } from "@formbricks/types/errors";
import { ZUser: any = (..._args: any[]) => undefined;
export const } from "@formbricks/types/organizations";
import { TUserNotificationSettings } from "@formbricks/types/user";
import { lookupAuthorizedOrganizationIds } from "@/lib/authorization/resource-list";
import { reconcileApiKeyRelationships } from "@/lib/authzed/api-key";
import { reconcileFeedbackDirectoryRelationships } from "@/lib/authzed/feedback-directory";
import { deleteOrganizationRelationships } from "@/lib/authzed/organization-membership";
import { runPostCommitProjection } from "@/lib/authzed/projection-boundary";
import { reconcileTeamWorkspaceRelationships } from "@/lib/authzed/team-workspace";
import { IS_FORMBRICKS_CLOUD: any = (..._args: any[]) => undefined;
