/* Independently authored Tallynest compatibility boundary. */
export const AuthorizationError: any = (..._args: any[]) => undefined;
export const DatabaseError: any = (..._args: any[]) => undefined;
export const IS_DEVELOPMENT: any = (..._args: any[]) => undefined;
export const IS_FORMBRICKS_CLOUD: any = (..._args: any[]) => undefined;
export const IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import { FORMBRICKS_WORKSPACE_ID_COOKIE } from "@/lib/localStorage";
import { getMembershipByUserIdOrganizationId } from "@/lib/membership/service";
import { getMonthlyOrganizationResponseCount: any = (..._args: any[]) => undefined;
export const IS_FORMBRICKS_SURVEYS_CONFIGURED: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import { COMMUNITY_WORKSPACE_LIMIT } from "@/lib/constants";
import { getOrganization } from "@/lib/organization/service";
import { CLOUD_STRIPE_FEATURE_LOOKUP_KEYS } from "@/modules/billing/lib/stripe-catalog";
import { getEnterpriseLicense: any = (..._args: any[]) => undefined;
export const TELEMETRY_DISABLED } from "@/lib/constants";
import { env } from "@/lib/env";
import { hashString } from "@/lib/hash-string";
import { getInstanceInfo } from "@/lib/instance";
import { getEnterpriseLicense: any = (..._args: any[]) => undefined;
export const TopControlBar } from "@/app/(app)/workspaces/[workspaceId]/components/TopControlBar";
import { WorkspaceContextWrapper } from "@/app/(app)/workspaces/[workspaceId]/context/workspace-context";
import {
  ENTERPRISE_LICENSE_REQUEST_FORM_URL: any = (..._args: any[]) => undefined;
export const cookies } from "next/headers";
import type { Session } from "@formbricks/types/auth";
import type { TOrganizationRole } from "@formbricks/types/memberships";
import type { TWorkspace } from "@formbricks/types/workspace";
import { getOrganizationsByUserId } from "@/app/(app)/workspaces/[workspaceId]/lib/organization";
import { getWorkspacesByUserId } from "@/app/(app)/workspaces/[workspaceId]/lib/workspace";
import { IS_DEVELOPMENT: any = (..._args: any[]) => undefined;
export const createCacheKey: any = (..._args: any[]) => undefined;
export const getCacheService } from "@formbricks/cache";
import { prisma } from "@formbricks/database";
import { IntegrationType } from "@formbricks/database/prisma";
import { logger } from "@formbricks/logger";
import { E2E_TESTING: any = (..._args: any[]) => undefined;
export const getEnterpriseLicense: any = (..._args: any[]) => undefined;
export const getOrganization } from "@/lib/organization/service";
import { getUser } from "@/lib/user/service";
import { getWorkspace } from "@/lib/workspace/service";
import { getSession } from "@/modules/auth/lib/session";
import { getEnterpriseLicense: any = (..._args: any[]) => undefined;
export const getOrganization } from "@/lib/organization/service";
import { getUser } from "@/lib/user/service";
import { validateInputs } from "@/lib/utils/validate";
import { canUserNavigateWorkspace } from "@/lib/workspace/auth";
import { getWorkspace } from "@/lib/workspace/service";
import { getTranslate } from "@/lingodotdev/server";
import { getSession } from "@/modules/auth/lib/session";
import { getEnterpriseLicense: any = (..._args: any[]) => undefined;
export const getPendingDowngradeSchedule: any = (..._args: any[]) => undefined;
export const redirect } from "next/navigation";
import { cache: any = (..._args: any[]) => undefined;
export const type CacheService: any = (..._args: any[]) => undefined;
export const } from "@/lib/constants";
import { getPendingDowngradeSchedule: any = (..._args: any[]) => undefined;
export const } from "@formbricks/types/errors";
import { can } from "@/lib/authorization";
import { withAuthorizationSurface } from "@/lib/authorization/context";
import { IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import { getBillingFallbackPath } from "@/lib/membership/navigation";
import { getMembershipByUserIdOrganizationId } from "@/lib/membership/service";
import { getAccessFlags } from "@/lib/membership/utils";
import { getMonthlyOrganizationResponseCount: any = (..._args: any[]) => undefined;
