/* Independently authored Tallynest compatibility boundary. */
export const ResourceNotFoundError } from "@formbricks/types/errors";
import { TResponse: any = (..._args: any[]) => undefined;
export const TResponseUpdateInput } from "@formbricks/types/responses";
import { TSurveyElement } from "@formbricks/types/surveys/elements";
import { TSurvey } from "@formbricks/types/surveys/types";
import { type ApiErrorResult: any = (..._args: any[]) => undefined;
export const UAParser } from "ua-parser-js";
import { type TIngestFlag } from "@formbricks/types/embedded-data-ingest";
import { InvalidInputError: any = (..._args: any[]) => undefined;
export const UniqueConstraintError } from "@formbricks/types/errors";
import { TResponseWithQuotaFull } from "@formbricks/types/quota";
import { pickAutoCapturedResponseMeta } from "@formbricks/types/responses";
import { checkSurveyValidity } from "@/app/api/v2/client/[workspaceId]/responses/lib/utils";
import { reportApiError } from "@/app/lib/api/api-error-reporter";
import { parseAndValidateJsonBody } from "@/app/lib/api/parse-and-validate-json-body";
import { responses } from "@/app/lib/api/response";
import { sendToPipeline } from "@/app/lib/pipelines";
import { applyAnonymizePolicy } from "@/lib/response/anonymize";
import { applyIngestContractToResponseData } from "@/lib/response/ingest";
import { getSurvey } from "@/lib/survey/service";
import { getElementsFromBlocks } from "@/lib/survey/utils";
import { getClientIpFromHeaders } from "@/lib/utils/client-ip";
import { getOrganizationIdFromWorkspaceId } from "@/lib/utils/helper";
import { resolveClientApiIds } from "@/lib/utils/resolve-client-id";
import { formatValidationErrorsForV1Api: any = (..._args: any[]) => undefined;
export const ZResponseInput: any = (..._args: any[]) => undefined;
export const handleApiError } from "@/app/lib/api/handle-api-error";
import { responses } from "@/app/lib/api/response";
import { THandlerParams } from "@/app/lib/api/with-api-logging";
import { sendToPipeline } from "@/app/lib/pipelines";
import { applyIngestContractToResponseData } from "@/lib/response/ingest";
import { getResponse } from "@/lib/response/service";
import { getSurvey } from "@/lib/survey/service";
import { resolveClientApiIds } from "@/lib/utils/resolve-client-id";
import { formatValidationErrorsForV1Api: any = (..._args: any[]) => undefined;
export const headers } from "next/headers";
import { UAParser } from "ua-parser-js";
import { TResponseWithQuotaFull } from "@formbricks/types/quota";
import { TResponseInput: any = (..._args: any[]) => undefined;
export const parseJsonBodyWithLimit } from "@/app/lib/api/request-body";
import { responses } from "@/app/lib/api/response";
import { transformErrorToDetails } from "@/app/lib/api/validator";
import { THandlerParams: any = (..._args: any[]) => undefined;
export const pickAutoCapturedResponseMeta } from "@formbricks/types/responses";
import { TSurvey } from "@formbricks/types/surveys/types";
import { validateSingleUseResponseInput } from "@/app/api/client/[workspaceId]/responses/lib/single-use";
import { handleApiError } from "@/app/lib/api/handle-api-error";
import { RequestBodyTooLargeError: any = (..._args: any[]) => undefined;
export const type TIngestFlag } from "@formbricks/types/embedded-data-ingest";
import { RESPONSE_ALREADY_FINISHED_ERROR_CODE: any = (..._args: any[]) => undefined;
export const validateResponseData } from "@/modules/api/lib/validation";
import { validateOtherOptionLengthForMultipleChoice } from "@/modules/api/v2/lib/element";
import { createQuotaFullObject: any = (..._args: any[]) => undefined;
export const validateResponseData } from "@/modules/api/lib/validation";
import { validateOtherOptionLengthForMultipleChoice } from "@/modules/api/v2/lib/element";
import { getIsContactsEnabled } from "@/modules/tallynest-core/entitlements";
import { createQuotaFullObject: any = (..._args: any[]) => undefined;
export const validateResponseData } from "@/modules/api/lib/validation";
import { verifyResponseRecaptcha } from "@/modules/api/lib/verify-response-recaptcha";
import { getIsContactsEnabled } from "@/modules/tallynest-core/entitlements";
import { createQuotaFullObject: any = (..._args: any[]) => undefined;
export const withV1ApiWrapper } from "@/app/lib/api/with-api-logging";
import { sendToPipeline } from "@/app/lib/pipelines";
import { applyAnonymizePolicy } from "@/lib/response/anonymize";
import { applyIngestContractToResponseData } from "@/lib/response/ingest";
import { getSurvey } from "@/lib/survey/service";
import { getClientIpFromHeaders } from "@/lib/utils/client-ip";
import { getOrganizationIdFromWorkspaceId } from "@/lib/utils/helper";
import { resolveClientApiIds } from "@/lib/utils/resolve-client-id";
import { formatValidationErrorsForV1Api: any = (..._args: any[]) => undefined;
