/* Independently authored Tallynest compatibility boundary. */
export const InvalidInputError: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import {
  TResponse: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import { TSurveyBlock } from "@formbricks/types/surveys/blocks";
import { TSurveyFilterCriteria } from "@formbricks/types/surveys/types";
import { reconcileEmbeddedData } from "@/lib/embedded-data/reconcile";
import { getOrganizationByWorkspaceId } from "@/lib/organization/service";
import { checkForInvalidMediaInBlocks } from "@/lib/survey/utils";
import { validateInputs } from "@/lib/utils/validate";
import { getTranslate } from "@/lingodotdev/server";
import { getIsQuotasEnabled } from "@/modules/tallynest-core/entitlements";
import { getQuotas: any = (..._args: any[]) => undefined;
export const ResourceNotFoundError } from "@formbricks/types/errors";
import { validateInputs } from "@/lib/utils/validate";
import { getQuota: any = (..._args: any[]) => undefined;
export const TResponseContact: any = (..._args: any[]) => undefined;
export const TResponseFilterCriteria: any = (..._args: any[]) => undefined;
export const TResponseUpdateInput: any = (..._args: any[]) => undefined;
export const TResponseWithQuotas: any = (..._args: any[]) => undefined;
export const ZOptionalNumber: any = (..._args: any[]) => undefined;
export const ZResponseFilterCriteria: any = (..._args: any[]) => undefined;
export const ZResponseUpdateInput: any = (..._args: any[]) => undefined;
export const ZString } from "@formbricks/types/common";
import { DatabaseError: any = (..._args: any[]) => undefined;
export const ZString } from "@formbricks/types/common";
import { type TIngestFlag: any = (..._args: any[]) => undefined;
export const cache: any = (..._args: any[]) => undefined;
export const createId } from "@paralleldrive/cuid2";
import { cache: any = (..._args: any[]) => undefined;
export const getIsContactsEnabled: any = (..._args: any[]) => undefined;
export const getIsQuotasEnabled: any = (..._args: any[]) => undefined;
export const getIsQuotasEnabled } from "@/modules/tallynest-core/entitlements";
import { getQuotas: any = (..._args: any[]) => undefined;
export const getIsSpamProtectionEnabled: any = (..._args: any[]) => undefined;
export const getIsWorkflowsEnabled: any = (..._args: any[]) => undefined;
export const getResponseFilteringValues } from "@/lib/response/service";
import { getSurvey } from "@/lib/survey/service";
import { getTagsByWorkspaceId } from "@/lib/tag/service";
import { authenticatedActionClient } from "@/lib/utils/action-client";
import { getOrganizationIdFromSurveyId: any = (..._args: any[]) => undefined;
export const getWorkspaceIdFromSurveyId } from "@/lib/utils/helper";
import { getIsQuotasEnabled } from "@/modules/tallynest-core/entitlements";
import { getQuotas: any = (..._args: any[]) => undefined;
export const mergeIngestFlags } from "@formbricks/types/embedded-data-ingest";
import { type TEmbeddedValueResponse } from "@formbricks/types/embedded-data-resolver";
import { DatabaseError: any = (..._args: any[]) => undefined;
export const z } from "zod";
import { ZId } from "@formbricks/types/common";
import { ResourceNotFoundError } from "@formbricks/types/errors";
import { ZResponseFilterCriteria } from "@formbricks/types/responses";
import { assertCan } from "@/lib/authorization";
import { capturePostHogEvent } from "@/lib/posthog";
import { getResponseDownloadFile: any = (..._args: any[]) => undefined;
export const } from "@/modules/tallynest-core/entitlements";
import { getQuotas: any = (..._args: any[]) => undefined;
export const } from "@formbricks/types/responses";
import { TSurvey } from "@formbricks/types/surveys/types";
import { TTag } from "@formbricks/types/tags";
import { getIsQuotasEnabled } from "@/modules/tallynest-core/entitlements";
import { reduceQuotaLimits: any = (..._args: any[]) => undefined;
