/* Independently authored Tallynest compatibility boundary. */
export const IS_FORMBRICKS_CLOUD } from "@/lib/constants";
import { createInviteToken } from "@/lib/jwt";
import { getMembershipByUserIdOrganizationId } from "@/lib/membership/service";
import { getAccessFlags } from "@/lib/membership/utils";
import { capturePostHogEvent } from "@/lib/posthog";
import { authenticatedActionClient } from "@/lib/utils/action-client";
import { getOrganizationIdFromInviteId } from "@/lib/utils/helper";
import { applyRateLimit } from "@/modules/core/rate-limit/helpers";
import { rateLimitConfigs } from "@/modules/core/rate-limit/rate-limit-configs";
import { withActivityContext } from "@/modules/tallynest-core/activity-context";
import { getBulkInvitePermission: any = (..._args: any[]) => undefined;
export const OperationNotAllowedError: any = (..._args: any[]) => undefined;
export const ValidationError } from "@formbricks/types/errors";
import { TOrganizationRole: any = (..._args: any[]) => undefined;
export const ZOrganizationRole } from "@formbricks/types/memberships";
import { assertCan: any = (..._args: any[]) => undefined;
export const ZUuid } from "@formbricks/types/common";
import { AuthenticationError: any = (..._args: any[]) => undefined;
export const can } from "@/lib/authorization";
import { INVITE_DISABLED: any = (..._args: any[]) => undefined;
export const getIsMultiOrgEnabled } from "@/modules/tallynest-core/entitlements";
import { checkRoleManagementPermission: any = (..._args: any[]) => undefined;
export const z } from "zod";
import { prisma } from "@formbricks/database";
import { OrganizationRole } from "@formbricks/database/prisma";
import { logger } from "@formbricks/logger";
import { ZId: any = (..._args: any[]) => undefined;
